HEADERS += \
    $$PWD/spdlog/include/spdlog/async.h \
    $$PWD/spdlog/include/spdlog/async_logger-inl.h \
    $$PWD/spdlog/include/spdlog/async_logger.h \
    $$PWD/spdlog/include/spdlog/cfg/argv.h \
    $$PWD/spdlog/include/spdlog/cfg/env.h \
    $$PWD/spdlog/include/spdlog/cfg/helpers-inl.h \
    $$PWD/spdlog/include/spdlog/cfg/helpers.h \
    $$PWD/spdlog/include/spdlog/common-inl.h \
    $$PWD/spdlog/include/spdlog/common.h \
    $$PWD/spdlog/include/spdlog/details/backtracer-inl.h \
    $$PWD/spdlog/include/spdlog/details/backtracer.h \
    $$PWD/spdlog/include/spdlog/details/circular_q.h \
    $$PWD/spdlog/include/spdlog/details/console_globals.h \
    $$PWD/spdlog/include/spdlog/details/file_helper-inl.h \
    $$PWD/spdlog/include/spdlog/details/file_helper.h \
    $$PWD/spdlog/include/spdlog/details/fmt_helper.h \
    $$PWD/spdlog/include/spdlog/details/log_msg-inl.h \
    $$PWD/spdlog/include/spdlog/details/log_msg.h \
    $$PWD/spdlog/include/spdlog/details/log_msg_buffer-inl.h \
    $$PWD/spdlog/include/spdlog/details/log_msg_buffer.h \
    $$PWD/spdlog/include/spdlog/details/mpmc_blocking_q.h \
    $$PWD/spdlog/include/spdlog/details/null_mutex.h \
    $$PWD/spdlog/include/spdlog/details/os-inl.h \
    $$PWD/spdlog/include/spdlog/details/os.h \
    $$PWD/spdlog/include/spdlog/details/periodic_worker-inl.h \
    $$PWD/spdlog/include/spdlog/details/periodic_worker.h \
    $$PWD/spdlog/include/spdlog/details/registry-inl.h \
    $$PWD/spdlog/include/spdlog/details/registry.h \
    $$PWD/spdlog/include/spdlog/details/synchronous_factory.h \
    $$PWD/spdlog/include/spdlog/details/tcp_client-windows.h \
    $$PWD/spdlog/include/spdlog/details/tcp_client.h \
    $$PWD/spdlog/include/spdlog/details/thread_pool-inl.h \
    $$PWD/spdlog/include/spdlog/details/thread_pool.h \
    $$PWD/spdlog/include/spdlog/details/windows_include.h \
    $$PWD/spdlog/include/spdlog/fmt/bin_to_hex.h \
    $$PWD/spdlog/include/spdlog/fmt/bundled/chrono.h \
    $$PWD/spdlog/include/spdlog/fmt/bundled/color.h \
    $$PWD/spdlog/include/spdlog/fmt/bundled/compile.h \
    $$PWD/spdlog/include/spdlog/fmt/bundled/core.h \
    $$PWD/spdlog/include/spdlog/fmt/bundled/format-inl.h \
    $$PWD/spdlog/include/spdlog/fmt/bundled/format.h \
    $$PWD/spdlog/include/spdlog/fmt/bundled/locale.h \
    $$PWD/spdlog/include/spdlog/fmt/bundled/os.h \
    $$PWD/spdlog/include/spdlog/fmt/bundled/ostream.h \
    $$PWD/spdlog/include/spdlog/fmt/bundled/posix.h \
    $$PWD/spdlog/include/spdlog/fmt/bundled/printf.h \
    $$PWD/spdlog/include/spdlog/fmt/bundled/ranges.h \
    $$PWD/spdlog/include/spdlog/fmt/chrono.h \
    $$PWD/spdlog/include/spdlog/fmt/fmt.h \
    $$PWD/spdlog/include/spdlog/fmt/ostr.h \
    $$PWD/spdlog/include/spdlog/formatter.h \
    $$PWD/spdlog/include/spdlog/fwd.h \
    $$PWD/spdlog/include/spdlog/logger-inl.h \
    $$PWD/spdlog/include/spdlog/logger.h \
    $$PWD/spdlog/include/spdlog/pattern_formatter-inl.h \
    $$PWD/spdlog/include/spdlog/pattern_formatter.h \
    $$PWD/spdlog/include/spdlog/sinks/android_sink.h \
    $$PWD/spdlog/include/spdlog/sinks/ansicolor_sink-inl.h \
    $$PWD/spdlog/include/spdlog/sinks/ansicolor_sink.h \
    $$PWD/spdlog/include/spdlog/sinks/base_sink-inl.h \
    $$PWD/spdlog/include/spdlog/sinks/base_sink.h \
    $$PWD/spdlog/include/spdlog/sinks/basic_file_sink-inl.h \
    $$PWD/spdlog/include/spdlog/sinks/basic_file_sink.h \
    $$PWD/spdlog/include/spdlog/sinks/daily_file_sink.h \
    $$PWD/spdlog/include/spdlog/sinks/dist_sink.h \
    $$PWD/spdlog/include/spdlog/sinks/dup_filter_sink.h \
    $$PWD/spdlog/include/spdlog/sinks/hourly_file_sink.h \
    $$PWD/spdlog/include/spdlog/sinks/msvc_sink.h \
    $$PWD/spdlog/include/spdlog/sinks/null_sink.h \
    $$PWD/spdlog/include/spdlog/sinks/ostream_sink.h \
    $$PWD/spdlog/include/spdlog/sinks/ringbuffer_sink.h \
    $$PWD/spdlog/include/spdlog/sinks/rotating_file_sink-inl.h \
    $$PWD/spdlog/include/spdlog/sinks/rotating_file_sink.h \
    $$PWD/spdlog/include/spdlog/sinks/sink-inl.h \
    $$PWD/spdlog/include/spdlog/sinks/sink.h \
    $$PWD/spdlog/include/spdlog/sinks/stdout_color_sinks-inl.h \
    $$PWD/spdlog/include/spdlog/sinks/stdout_color_sinks.h \
    $$PWD/spdlog/include/spdlog/sinks/stdout_sinks-inl.h \
    $$PWD/spdlog/include/spdlog/sinks/stdout_sinks.h \
    $$PWD/spdlog/include/spdlog/sinks/syslog_sink.h \
    $$PWD/spdlog/include/spdlog/sinks/systemd_sink.h \
    $$PWD/spdlog/include/spdlog/sinks/tcp_sink.h \
    $$PWD/spdlog/include/spdlog/sinks/win_eventlog_sink.h \
    $$PWD/spdlog/include/spdlog/sinks/wincolor_sink-inl.h \
    $$PWD/spdlog/include/spdlog/sinks/wincolor_sink.h \
    $$PWD/spdlog/include/spdlog/spdlog-inl.h \
    $$PWD/spdlog/include/spdlog/spdlog.h \
    $$PWD/spdlog/include/spdlog/stopwatch.h \
    $$PWD/spdlog/include/spdlog/tweakme.h \
    $$PWD/spdlog/include/spdlog/version.h

